@startuml

class Car {
    +Car(String id, String model, String brand)
    +String getId()
    +String getModel()
    +String getBrand()

    -final String _id
    -final String _model
    -final String _brand
}

class CarRepository {
    +Car getFromDb(String carId)
    +List<Car> getAllCars()
}

class CarService {
    +Car getBestCar()
}

class CarFormatter {
    +String getCarsNames(List<Car> cars)
}

class Client {
    +void displayBestCarInfo()
}

CarRepository --> "*" Car
CarService --> CarRepository
CarFormatter --> CarRepository

CarService ..> Car: use
CarFormatter ..> Car: use

Client ..> CarService: use
Client ..> CarFormatter: use

@enduml
